# Generated by Django 5.2.4 on 2025-12-28 05:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvesteeCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('cin', models.CharField(blank=True, max_length=21, null=True, unique=True, verbose_name='CIN')),
                ('incorporation_date', models.DateField(blank=True, null=True)),
                ('sector', models.CharField(blank=True, max_length=100, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('total_funding_raised', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyFinancials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_year', models.CharField(help_text='e.g. 2023-2024', max_length=9)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('ebitda', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('net_profit', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('investee_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financials', to='investee_companies.investeecompany')),
            ],
        ),
        migrations.CreateModel(
            name='ShareCapital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_type', models.CharField(choices=[('EQUITY', 'Equity Shares'), ('PREF', 'Preference Shares'), ('CCPS', 'Compulsorily Convertible Preference'), ('OCPS', 'Optionally Convertible Preference'), ('CCD', 'Compulsorily Convertible Debentures')], default='EQUITY', max_length=10)),
                ('class_name', models.CharField(default='Common', help_text='e.g. Series A, Common', max_length=50)),
                ('face_value', models.DecimalField(decimal_places=2, default=10.0, max_digits=10)),
                ('authorized_capital', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('issued_shares', models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='Total Issued Units')),
                ('as_on_date', models.DateField(default=django.utils.timezone.now, verbose_name='Structure As On')),
                ('investee_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_classes', to='investee_companies.investeecompany')),
            ],
        ),
        migrations.CreateModel(
            name='CorporateAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('SPLIT', 'Stock Split'), ('BONUS', 'Bonus Issue'), ('MERGER', 'Merger / Amalgamation')], max_length=20)),
                ('action_date', models.DateField()),
                ('ratio_from', models.IntegerField(default=1)),
                ('ratio_to', models.IntegerField(default=1)),
                ('is_executed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('investee_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corporate_actions', to='investee_companies.investeecompany')),
                ('target_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='investee_companies.sharecapital')),
            ],
        ),
        migrations.CreateModel(
            name='Shareholding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holder_name', models.CharField(blank=True, help_text='Manual entry for non-AIF holders', max_length=255)),
                ('number_of_shares', models.DecimalField(decimal_places=4, max_digits=18)),
                ('investee_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investee_companies.investeecompany')),
                ('investor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='investors.investor')),
                ('share_capital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='investee_companies.sharecapital')),
            ],
        ),
        migrations.CreateModel(
            name='ValuationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valuation_date', models.DateField()),
                ('report_file', models.FileField(blank=True, null=True, upload_to='valuations/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('investee_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investee_companies.investeecompany')),
            ],
        ),
        migrations.CreateModel(
            name='ShareValuation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('per_share_value', models.DecimalField(decimal_places=4, max_digits=18)),
                ('share_capital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investee_companies.sharecapital')),
                ('valuation_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_values', to='investee_companies.valuationreport')),
            ],
        ),
    ]
