# Generated by Django 5.2.4 on 2025-09-02 05:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investors', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvesteeCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('cin', models.CharField(max_length=21, unique=True, verbose_name='Corporate Identification Number')),
                ('incorporation_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='CorporateAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('SPLIT', 'Stock Split'), ('BONUS', 'Bonus Issue'), ('CONV', 'Conversion')], max_length=20)),
                ('action_date', models.DateField()),
                ('details', models.TextField()),
                ('share_type', models.CharField(blank=True, choices=[('EQ', 'Equity Shares'), ('PREF', 'Preference Shares'), ('CONV', 'Convertible Instruments')], max_length=4, null=True)),
                ('ratio', models.CharField(blank=True, max_length=50, null=True)),
                ('from_share_type', models.CharField(blank=True, choices=[('EQ', 'Equity Shares'), ('PREF', 'Preference Shares'), ('CONV', 'Convertible Instruments')], max_length=4, null=True)),
                ('to_share_type', models.CharField(blank=True, choices=[('EQ', 'Equity Shares'), ('PREF', 'Preference Shares'), ('CONV', 'Convertible Instruments')], max_length=4, null=True)),
                ('number_of_shares_converted', models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True)),
                ('investee_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corporate_actions', to='investee_companies.investeecompany')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyFinancials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_date', models.DateField(help_text='End date of the financial period, e.g., end of a quarter.')),
                ('revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('ebitda', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='EBITDA')),
                ('net_income', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('investee_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financials', to='investee_companies.investeecompany')),
            ],
            options={
                'verbose_name_plural': 'Company Financials',
                'ordering': ['-period_date'],
            },
        ),
        migrations.CreateModel(
            name='Shareholding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holder_name', models.CharField(blank=True, help_text='If not linked to an Investor record, type the shareholder name', max_length=255)),
                ('share_type', models.CharField(choices=[('EQ', 'Equity Shares'), ('PREF', 'Preference Shares'), ('CONV', 'Convertible Instruments')], default='EQ', max_length=10)),
                ('number_of_shares', models.PositiveBigIntegerField()),
                ('face_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('acquisition_price', models.DecimalField(blank=True, decimal_places=4, help_text='Price per share at acquisition (optional)', max_digits=18, null=True)),
                ('acquisition_date', models.DateField(blank=True, null=True)),
                ('certificate_or_demat', models.CharField(blank=True, help_text='Certificate number or Demat account', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('investee_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shareholdings', to='investee_companies.investeecompany')),
                ('investor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investee_shareholdings', to='investors.investor')),
            ],
            options={
                'verbose_name': 'Shareholding',
                'verbose_name_plural': 'Shareholdings',
                'unique_together': {('investee_company', 'investor', 'holder_name', 'share_type')},
            },
        ),
        migrations.CreateModel(
            name='ValuationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valuation_date', models.DateField(default=django.utils.timezone.now)),
                ('total_market_value', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('report_file', models.FileField(blank=True, null=True, upload_to='valuation_reports/')),
                ('investee_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valuation_reports', to='investee_companies.investeecompany')),
            ],
        ),
        migrations.CreateModel(
            name='ShareValuation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('per_share_value', models.DecimalField(decimal_places=2, max_digits=18)),
                ('share_capital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valuations', to='investee_companies.shareholding')),
                ('valuation_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_valuations', to='investee_companies.valuationreport')),
            ],
        ),
    ]
