# Generated by Django 5.2.4 on 2025-08-28 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investee_companies', '0001_initial'),
        ('investors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shareholding',
            name='investor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investee_shareholdings', to='investors.investor'),
        ),
        migrations.AddField(
            model_name='sharevaluation',
            name='share_capital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valuations', to='investee_companies.sharecapital'),
        ),
        migrations.AddField(
            model_name='valuationreport',
            name='investee_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valuation_reports', to='investee_companies.investeecompany'),
        ),
        migrations.AddField(
            model_name='sharevaluation',
            name='valuation_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_valuations', to='investee_companies.valuationreport'),
        ),
        migrations.AlterUniqueTogether(
            name='shareholding',
            unique_together={('investee_company', 'investor', 'holder_name', 'share_type')},
        ),
    ]
