# Generated by Django 5.2.4 on 2025-08-29 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investee_companies', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharecapital',
            name='investee_company',
        ),
        migrations.AlterField(
            model_name='sharevaluation',
            name='share_capital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valuations', to='investee_companies.shareholding'),
        ),
        migrations.AlterField(
            model_name='shareholding',
            name='share_type',
            field=models.CharField(choices=[('EQ', 'Equity Shares'), ('PREF', 'Preference Shares'), ('CONV', 'Convertible Instruments')], default='EQ', max_length=10),
        ),
    ]
