# Generated by Django 5.2.4 on 2025-08-29 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investee_companies', '0003_remove_sharecapital_investee_company_and_more'),
        ('transactions', '0003_alter_purchasetransaction_share_capital_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShareCapital',
        ),
    ]
