# Generated by Django 5.2.4 on 2025-09-02 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Manager name (init)', max_length=255, null=True)),
                ('dummy_field', models.BooleanField(default=False)),
            ],
        ),
    ]
