# Generated by Django 5.2.4 on 2025-12-26 20:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='ISO 4217 Code (e.g., USD, INR)', max_length=3, unique=True)),
                ('symbol', models.CharField(help_text='Symbol (e.g., $, ₹)', max_length=5)),
                ('name', models.CharField(max_length=50)),
                ('is_base', models.BooleanField(default=False, help_text='Is this the system reporting currency (e.g. INR)?')),
            ],
            options={
                'verbose_name_plural': 'Currencies',
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('rate', models.DecimalField(decimal_places=6, help_text='Conversion rate to Base Currency', max_digits=20)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='currencies.currency')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('currency', 'date')},
            },
        ),
    ]
