# Generated by Django 5.2.4 on 2025-08-28 18:09

import django.db.models.deletion
import django.utils.timezone
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('pan', models.CharField(blank=True, help_text='PAN of Investor', max_length=10, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('type', models.CharField(choices=[('SPONSOR', 'Sponsor / Manager'), ('LP', 'Limited Partner (Investor)'), ('OTHER', 'Other')], default='LP', max_length=20)),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
        migrations.CreateModel(
            name='FATCADeclaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('declaration_status', models.BooleanField(default=False, verbose_name='FATCA Declaration Submitted')),
                ('date_submitted', models.DateField(default=django.utils.timezone.now)),
                ('is_us_person', models.BooleanField(default=False, verbose_name='Is a US Person')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fatca_declarations', to='investors.investor')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='investor_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='investors.investor')),
            ],
        ),
        migrations.CreateModel(
            name='CommunicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('communication_date', models.DateField(default=django.utils.timezone.now)),
                ('communication_type', models.CharField(choices=[('EMAIL', 'Email'), ('CALL', 'Call'), ('MEETING', 'Meeting')], max_length=10)),
                ('notes', models.TextField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='investors.investor')),
            ],
            options={
                'ordering': ['-communication_date'],
            },
        ),
        migrations.CreateModel(
            name='InvestorBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=50)),
                ('ifsc_code', models.CharField(max_length=11, verbose_name='IFSC Code')),
                ('is_primary', models.BooleanField(default=False)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='investors.investor')),
            ],
        ),
        migrations.CreateModel(
            name='KYCStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kyc_status', models.BooleanField(default=False, verbose_name='KYC Completed')),
                ('investor_type', models.CharField(choices=[('IND', 'Individual'), ('NON-IND', 'Non-Individual')], max_length=10)),
                ('date_completed', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('investor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_status', to='investors.investor')),
            ],
        ),
    ]
