# Generated by Django 5.2.4 on 2025-12-28 19:06

import django.db.models.deletion
import investors.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manager_entities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('investor_type', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('HUF', 'HUF'), ('COMPANY', 'Corporate Body'), ('LLP', 'LLP'), ('TRUST', 'Trust'), ('NRI', 'NRI'), ('FPI', 'FPI / Foreign Entity')], default='INDIVIDUAL', max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('pan', models.CharField(help_text='Permanent Account Number', max_length=10, unique=True)),
                ('demat_account_no', models.CharField(blank=True, max_length=100, null=True)),
                ('dp_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='DP ID')),
                ('accreditation_status', models.CharField(choices=[('NOT_APPLICABLE', 'Not Applicable'), ('VALID', 'Valid Accreditation'), ('EXPIRED', 'Accreditation Expired')], default='NOT_APPLICABLE', max_length=20)),
                ('accreditation_expiry', models.DateField(blank=True, null=True)),
                ('kyc_status', models.CharField(choices=[('PENDING', 'Pending'), ('SUBMITTED', 'Submitted'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('risk_appetite', models.CharField(blank=True, choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=50)),
                ('manager_entities', models.ManyToManyField(blank=True, related_name='investors', to='manager_entities.managerentity')),
            ],
        ),
        migrations.CreateModel(
            name='InvestorDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('PAN', 'PAN Card'), ('AADHAR', 'Aadhar Card'), ('PASSPORT', 'Passport'), ('BANK_PROOF', 'Bank Proof'), ('ACCREDITATION_CERT', 'Accreditation Certificate'), ('FATCA_CRS', 'FATCA / CRS Declaration'), ('OTHER', 'Other')], max_length=20)),
                ('file', models.FileField(upload_to=investors.models.investor_doc_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='investors.investor')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InvestorBankDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=50)),
                ('ifsc_code', models.CharField(max_length=11)),
                ('swift_code', models.CharField(blank=True, help_text='Required for FPI/NRI', max_length=20, null=True)),
                ('account_holder_name', models.CharField(max_length=255)),
                ('is_primary', models.BooleanField(default=False)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_details', to='investors.investor')),
                ('verification_doc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='investors.investordocument')),
            ],
        ),
        migrations.CreateModel(
            name='Nominee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('relation', models.CharField(max_length=50)),
                ('dob', models.DateField(help_text='Required to determine if minor')),
                ('allocation_percentage', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('guardian_name', models.CharField(blank=True, help_text='If nominee is a minor', max_length=255, null=True)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominees', to='investors.investor')),
            ],
        ),
    ]
