# Generated by Django 5.2.4 on 2025-12-26 20:34

import django.db.models.deletion
import investors.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('investor_type', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('HUF', 'HUF'), ('COMPANY', 'Corporate Body'), ('LLP', 'LLP'), ('TRUST', 'Trust'), ('NRI', 'NRI'), ('FPI', 'FPI / Foreign Entity')], default='INDIVIDUAL', max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('pan', models.CharField(help_text='Permanent Account Number', max_length=10, unique=True)),
                ('demat_account_no', models.CharField(blank=True, max_length=100, null=True)),
                ('dp_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='DP ID')),
                ('accreditation_status', models.CharField(choices=[('NOT_APPLICABLE', 'Not Applicable'), ('VALID', 'Valid Accreditation'), ('EXPIRED', 'Accreditation Expired')], default='NOT_APPLICABLE', max_length=20)),
                ('accreditation_expiry', models.DateField(blank=True, null=True)),
                ('kyc_status', models.CharField(choices=[('PENDING', 'Pending'), ('SUBMITTED', 'Submitted'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('risk_appetite', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='InvestorDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('PAN', 'PAN Card'), ('AADHAR', 'Aadhar Card'), ('PASSPORT', 'Passport'), ('BANK_PROOF', 'Bank Proof'), ('ACCREDITATION_CERT', 'Accreditation Certificate'), ('FATCA_CRS', 'FATCA / CRS Declaration'), ('OTHER', 'Other')], max_length=20)),
                ('file', models.FileField(upload_to=investors.models.investor_doc_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='investors.investor')),
            ],
        ),
    ]
