# Generated by Django 5.2.4 on 2025-08-28 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('ACCOUNT_FORM', 'Account Form'), ('PAN', 'PAN'), ('AADHAR', 'Aadhar'), ('MOA', 'Memorandum of Association'), ('AOA', 'Articles of Association'), ('COI', 'Certificate of Incorporation'), ('OTHER', 'Other')], max_length=32)),
                ('file', models.FileField(upload_to='investors/%Y/%m/%d/')),
                ('is_verified', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='investors.investor')),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'unique_together': {('investor', 'doc_type')},
            },
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
