# Generated by Django 5.2.4 on 2025-12-23 16:38

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('currencies', '0001_initial'),
        ('investee_companies', '0001_initial'),
        ('investors', '0001_initial'),
        ('manager_entities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('jurisdiction', models.CharField(choices=[('DOMESTIC', 'SEBI (Domestic)'), ('IFSC', 'IFSCA (GIFT City)')], default='DOMESTIC', max_length=10)),
                ('scheme_type', models.CharField(choices=[('MAIN', 'Main AIF Scheme'), ('CIV', 'Co-Investment Vehicle (CIV)'), ('ANGEL', 'Angel Fund Segment'), ('AI_ONLY', 'Accredited Investor Only Fund')], default='MAIN', max_length=10)),
                ('sebi_registration_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('category', models.CharField(choices=[('CAT_I', 'Category I'), ('CAT_II', 'Category II'), ('CAT_III', 'Category III')], max_length=10)),
                ('corpus', models.DecimalField(decimal_places=2, help_text='Total fund corpus', max_digits=18)),
                ('sponsor_commitment', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('date_of_inception', models.DateField(default=django.utils.timezone.now)),
                ('target_close_date', models.DateField(blank=True, null=True)),
                ('currency', models.ForeignKey(default=1, help_text='The functional currency of this fund.', on_delete=django.db.models.deletion.PROTECT, related_name='funds', to='currencies.currency')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='funds', to='manager_entities.managerentity')),
                ('parent_fund', models.ForeignKey(blank=True, help_text='Required for CIV schemes', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_schemes', to='funds.fund')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='documents/')),
                ('is_demat_advice', models.BooleanField(default=False, help_text='Tick if this is a Demat holding confirmation')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('investor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fund_documents', to='investors.investor')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='funds.fund')),
            ],
        ),
        migrations.CreateModel(
            name='NavSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as_on_date', models.DateField(default=django.utils.timezone.now)),
                ('nav_per_unit', models.DecimalField(decimal_places=4, max_digits=18)),
                ('aum', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('units_outstanding', models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=18)),
                ('is_first_close_nav', models.BooleanField(default=False)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nav_history', to='funds.fund')),
            ],
        ),
        migrations.CreateModel(
            name='StewardshipEngagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engagement_date', models.DateField(default=django.utils.timezone.now)),
                ('topic', models.CharField(help_text='e.g., Board Composition, ESG Breach, Financial Performance', max_length=255)),
                ('description', models.TextField(help_text='Summary of intervention/escalation with the board')),
                ('outcome', models.TextField(blank=True, null=True)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funds.fund')),
                ('investee_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investee_companies.investeecompany')),
            ],
            options={
                'verbose_name': 'Stewardship Engagement',
            },
        ),
    ]
