# Generated by Django 5.2.4 on 2025-12-26 20:34

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('currencies', '0001_initial'),
        ('investee_companies', '0001_initial'),
        ('investors', '0001_initial'),
        ('manager_entities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sebi_registration_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('category', models.CharField(choices=[('CAT_I', 'Category I (Venture/Social)'), ('CAT_II', 'Category II (PE/Debt)'), ('CAT_III', 'Category III (Hedge/Public)')], default='CAT_II', max_length=20)),
                ('jurisdiction', models.CharField(choices=[('DOMESTIC', 'SEBI (Domestic)'), ('IFSC', 'IFSCA (GIFT City)')], default='DOMESTIC', max_length=20)),
                ('scheme_type', models.CharField(choices=[('MAIN', 'Main AIF Scheme'), ('CIV', 'Co-Investment Vehicle (CIV)'), ('ANGEL', 'Angel Fund Segment'), ('AI_ONLY', 'Accredited Investor Only Fund')], default='MAIN', max_length=20)),
                ('corpus', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Target Fund Size', max_digits=20)),
                ('sponsor_commitment', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="Manager's Skin in the Game", max_digits=20)),
                ('date_of_inception', models.DateField(default=django.utils.timezone.now)),
                ('target_close_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('currency', models.ForeignKey(default=1, help_text='Functional currency of the fund', on_delete=django.db.models.deletion.PROTECT, related_name='funds', to='currencies.currency')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_funds', to=settings.AUTH_USER_MODEL)),
                ('manager_entity', models.ForeignKey(help_text='Manager entity under which this fund is registered', on_delete=django.db.models.deletion.PROTECT, related_name='funds', to='manager_entities.managerentity')),
                ('parent_fund', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_schemes', to='funds.fund')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='fund_documents/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_demat_advice', models.BooleanField(default=False)),
                ('investor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fund_documents', to='investors.investor')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='funds.fund')),
            ],
        ),
        migrations.CreateModel(
            name='InvestorPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_units', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=20)),
                ('total_capital_contributed', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cap_table', to='funds.fund')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='investors.investor')),
            ],
            options={
                'verbose_name': 'Cap Table Entry',
                'verbose_name_plural': 'Cap Table Entries',
            },
        ),
        migrations.CreateModel(
            name='NavSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as_on_date', models.DateField()),
                ('nav_per_unit', models.DecimalField(decimal_places=4, max_digits=15)),
                ('aum', models.DecimalField(decimal_places=2, help_text='Assets Under Management', max_digits=20)),
                ('units_outstanding', models.DecimalField(decimal_places=4, max_digits=18)),
                ('is_first_close_nav', models.BooleanField(default=False, help_text='Is this the NAV at First Close?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nav_history', to='funds.fund')),
            ],
            options={
                'ordering': ['-as_on_date'],
            },
        ),
        migrations.CreateModel(
            name='StewardshipEngagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engagement_date', models.DateField(default=django.utils.timezone.now)),
                ('topic', models.CharField(help_text='e.g. ESG, Governance, Strategy', max_length=255)),
                ('description', models.TextField()),
                ('outcome', models.TextField(blank=True, help_text='Result of the intervention')),
                ('status', models.CharField(choices=[('OPEN', 'Open/Ongoing'), ('RESOLVED', 'Resolved/Closed'), ('ESCALATED', 'Escalated to Board')], default='OPEN', max_length=20)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stewardship_logs', to='funds.fund')),
                ('investee_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investee_companies.investeecompany')),
            ],
        ),
        migrations.CreateModel(
            name='UnitIssuance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units_issued', models.DecimalField(decimal_places=4, max_digits=20)),
                ('nav_at_issuance', models.DecimalField(decimal_places=4, max_digits=12)),
                ('date_issued', models.DateField(auto_now_add=True)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issuances', to='funds.investorposition')),
            ],
        ),
    ]
