# Generated by Django 5.2.4 on 2025-08-28 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funds', '0001_initial'),
        ('investors', '0001_initial'),
        ('manager_entities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='investor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fund_documents', to='investors.investor'),
        ),
        migrations.AddField(
            model_name='fund',
            name='manager',
            field=models.ForeignKey(blank=True, help_text='Fund Manager Entity', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='funds', to='manager_entities.managerentity'),
        ),
        migrations.AddField(
            model_name='document',
            name='fund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='funds.fund'),
        ),
    ]
