# Generated by Django 5.2.4 on 2025-12-28 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funds', '0001_initial'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitissuance',
            name='receipt',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='unit_issuance', to='transactions.drawdownreceipt'),
        ),
        migrations.AlterUniqueTogether(
            name='investorposition',
            unique_together={('fund', 'investor')},
        ),
        migrations.AlterUniqueTogether(
            name='navsnapshot',
            unique_together={('fund', 'as_on_date')},
        ),
    ]
