# Generated by Django 5.2.4 on 2025-12-24 19:12

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0001_initial'),
        ('funds', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='navsnapshot',
            options={'ordering': ['-as_on_date']},
        ),
        migrations.AlterModelOptions(
            name='stewardshipengagement',
            options={},
        ),
        migrations.AddField(
            model_name='fund',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='navsnapshot',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stewardshipengagement',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open/Ongoing'), ('RESOLVED', 'Resolved/Closed'), ('ESCALATED', 'Escalated to Board')], default='OPEN', max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='fund_documents/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='is_demat_advice',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fund',
            name='category',
            field=models.CharField(choices=[('CAT_I', 'Category I (Venture/Social)'), ('CAT_II', 'Category II (PE/Debt)'), ('CAT_III', 'Category III (Hedge/Public)')], default='CAT_II', max_length=20),
        ),
        migrations.AlterField(
            model_name='fund',
            name='corpus',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Target Fund Size', max_digits=20),
        ),
        migrations.AlterField(
            model_name='fund',
            name='currency',
            field=models.ForeignKey(default=1, help_text='Functional currency of the fund', on_delete=django.db.models.deletion.PROTECT, related_name='funds', to='currencies.currency'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='jurisdiction',
            field=models.CharField(choices=[('DOMESTIC', 'SEBI (Domestic)'), ('IFSC', 'IFSCA (GIFT City)')], default='DOMESTIC', max_length=20),
        ),
        migrations.AlterField(
            model_name='fund',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_funds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fund',
            name='parent_fund',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_schemes', to='funds.fund'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='scheme_type',
            field=models.CharField(choices=[('MAIN', 'Main AIF Scheme'), ('CIV', 'Co-Investment Vehicle (CIV)'), ('ANGEL', 'Angel Fund Segment'), ('AI_ONLY', 'Accredited Investor Only Fund')], default='MAIN', max_length=20),
        ),
        migrations.AlterField(
            model_name='fund',
            name='sebi_registration_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='fund',
            name='sponsor_commitment',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="Manager's Skin in the Game", max_digits=20),
        ),
        migrations.AlterField(
            model_name='navsnapshot',
            name='as_on_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='navsnapshot',
            name='aum',
            field=models.DecimalField(decimal_places=2, help_text='Assets Under Management', max_digits=20),
        ),
        migrations.AlterField(
            model_name='navsnapshot',
            name='is_first_close_nav',
            field=models.BooleanField(default=False, help_text='Is this the NAV at First Close?'),
        ),
        migrations.AlterField(
            model_name='navsnapshot',
            name='nav_per_unit',
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name='navsnapshot',
            name='units_outstanding',
            field=models.DecimalField(decimal_places=4, max_digits=18),
        ),
        migrations.AlterField(
            model_name='stewardshipengagement',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='stewardshipengagement',
            name='fund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stewardship_logs', to='funds.fund'),
        ),
        migrations.AlterField(
            model_name='stewardshipengagement',
            name='outcome',
            field=models.TextField(blank=True, help_text='Result of the intervention'),
        ),
        migrations.AlterField(
            model_name='stewardshipengagement',
            name='topic',
            field=models.CharField(help_text='e.g. ESG, Governance, Strategy', max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='navsnapshot',
            unique_together={('fund', 'as_on_date')},
        ),
    ]
