# Generated by Django 5.2.4 on 2025-08-30 20:16

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NAVHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('nav_per_unit', models.DecimalField(decimal_places=4, help_text='NAV per unit', max_digits=18)),
                ('total_aum', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total Assets Under Management', max_digits=18)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nav_history', to='funds.fund')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('fund', 'date')},
            },
        ),
    ]
