# Generated by Django 5.2.4 on 2025-08-28 18:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funds', '0001_initial'),
        ('investee_companies', '0001_initial'),
        ('investors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapitalCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_date', models.DateField()),
                ('amount_called', models.DecimalField(decimal_places=2, max_digits=18)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capital_calls', to='funds.fund')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capital_calls', to='investors.investor')),
            ],
            options={
                'ordering': ['-call_date'],
            },
        ),
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distribution_date', models.DateField()),
                ('amount_distributed', models.DecimalField(decimal_places=2, max_digits=18)),
                ('notes', models.TextField(blank=True, null=True)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='funds.fund')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='investors.investor')),
            ],
            options={
                'ordering': ['-distribution_date'],
            },
        ),
        migrations.CreateModel(
            name='DrawdownReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_date', models.DateField()),
                ('amount_received', models.DecimalField(decimal_places=2, max_digits=18)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drawdown_receipts', to='funds.fund')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drawdown_receipts', to='investors.investor')),
            ],
            options={
                'ordering': ['-receipt_date'],
            },
        ),
        migrations.CreateModel(
            name='InvestorCommitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commitment_date', models.DateField()),
                ('amount_committed', models.DecimalField(decimal_places=2, max_digits=18)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commitments', to='funds.fund')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commitments', to='investors.investor')),
            ],
            options={
                'ordering': ['-commitment_date'],
            },
        ),
        migrations.CreateModel(
            name='InvestorUnitIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField(default=django.utils.timezone.now)),
                ('units_issued', models.DecimalField(decimal_places=4, max_digits=18)),
                ('price_per_unit', models.DecimalField(decimal_places=6, max_digits=18)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_issues', to='funds.fund')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_issues', to='investors.investor')),
            ],
            options={
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18, verbose_name='Qty of Shares')),
                ('purchase_rate', models.DecimalField(decimal_places=4, max_digits=18)),
                ('face_value', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('purchase_date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('reversed', 'Reversed')], default='posted', max_length=20)),
                ('import_batch_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('external_ref', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('fees', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('taxes', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('fx_rate', models.DecimalField(decimal_places=6, default=1, max_digits=18)),
                ('unique_hash', models.CharField(db_index=True, editable=False, max_length=64)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='funds.fund')),
                ('investee_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases_by_fund', to='investee_companies.investeecompany')),
                ('share_capital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='investee_companies.sharecapital')),
            ],
            options={
                'ordering': ['-purchase_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RedemptionTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18, verbose_name='Qty of Shares')),
                ('redemption_rate', models.DecimalField(decimal_places=4, max_digits=18)),
                ('redemption_date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('reversed', 'Reversed')], default='posted', max_length=20)),
                ('import_batch_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('external_ref', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='funds.fund')),
                ('investee_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions_by_fund', to='investee_companies.investeecompany')),
                ('share_capital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='investee_companies.sharecapital')),
            ],
            options={
                'ordering': ['-redemption_date', '-id'],
            },
        ),
    ]
