# Generated by Django 5.2.4 on 2025-12-25 20:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('currencies', '0001_initial'),
        ('funds', '0001_initial'),
        ('investee_companies', '0001_initial'),
        ('investors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapitalCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_date', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField()),
                ('amount_called', models.DecimalField(decimal_places=2, max_digits=14)),
                ('purpose', models.CharField(max_length=255)),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funds.fund')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investors.investor')),
            ],
        ),
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distribution_date', models.DateField(default=django.utils.timezone.now)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('distribution_type', models.CharField(choices=[('INTEREST', 'Interest'), ('DIVIDEND', 'Dividend'), ('PRINCIPAL', 'Principal Return')], default='PRINCIPAL', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funds.fund')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investors.investor')),
            ],
        ),
        migrations.CreateModel(
            name='DrawdownReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_date', models.DateField(default=django.utils.timezone.now)),
                ('amount_received', models.DecimalField(decimal_places=2, max_digits=14)),
                ('payment_mode', models.CharField(choices=[('NEFT', 'NEFT'), ('RTGS', 'RTGS'), ('SWIFT', 'SWIFT'), ('CHEQUE', 'Cheque')], default='NEFT', max_length=10)),
                ('transaction_ref', models.CharField(help_text='UTR/IMPS Ref', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('capital_call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='transactions.capitalcall')),
            ],
        ),
        migrations.CreateModel(
            name='InvestorCommitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_committed', models.DecimalField(decimal_places=2, max_digits=14)),
                ('commitment_date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commitments', to='funds.fund')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commitments', to='investors.investor')),
            ],
        ),
        migrations.CreateModel(
            name='InvestorUnitIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField(default=django.utils.timezone.now)),
                ('units_issued', models.DecimalField(decimal_places=4, max_digits=18)),
                ('price_per_unit', models.DecimalField(decimal_places=4, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funds.fund')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investors.investor')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField(default=django.utils.timezone.now)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=14)),
                ('price_per_share', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='currencies.currency')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funds.fund')),
                ('investee_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investee_companies.investeecompany')),
                ('share_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='investee_companies.sharecapital')),
            ],
        ),
        migrations.CreateModel(
            name='RedemptionTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField(default=django.utils.timezone.now)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=14)),
                ('price_per_share', models.DecimalField(decimal_places=2, max_digits=14)),
                ('cost_basis', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('realized_gain', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funds.fund')),
                ('investee_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investee_companies.investeecompany')),
                ('share_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='investee_companies.sharecapital')),
            ],
        ),
    ]
