# Generated by Django 5.2.4 on 2025-12-23 16:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funds', '0001_initial'),
        ('investee_companies', '0001_initial'),
        ('investors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapitalCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('amount_called', models.DecimalField(decimal_places=2, max_digits=18)),
                ('call_date', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funds.fund')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capital_calls', to='investors.investor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('tax_withheld', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('paid_date', models.DateField(default=django.utils.timezone.now)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funds.fund')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='investors.investor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DrawdownReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('amount_received', models.DecimalField(decimal_places=2, max_digits=18)),
                ('receipt_date', models.DateField(default=django.utils.timezone.now)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('capital_call', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='transactions.capitalcall')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funds.fund')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drawdown_receipts', to='investors.investor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InvestorCommitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('amount_committed', models.DecimalField(decimal_places=2, max_digits=18)),
                ('commitment_date', models.DateField(default=django.utils.timezone.now)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funds.fund')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commitments', to='investors.investor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InvestorUnitIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('units_issued', models.DecimalField(decimal_places=4, max_digits=18)),
                ('nav_at_issue', models.DecimalField(decimal_places=4, max_digits=18)),
                ('issue_date', models.DateField(default=django.utils.timezone.now)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funds.fund')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='investors.investor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('price', models.DecimalField(decimal_places=4, help_text='Price per share', max_digits=18)),
                ('trade_date', models.DateField(default=django.utils.timezone.now)),
                ('settle_date', models.DateField(blank=True, null=True)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funds.fund')),
                ('investee_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='investee_companies.investeecompany')),
                ('share_capital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='investee_companies.sharecapital')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RedemptionTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('price', models.DecimalField(decimal_places=4, help_text='Selling price per share', max_digits=18)),
                ('trade_date', models.DateField(default=django.utils.timezone.now)),
                ('cost_basis', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('realized_gain', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funds.fund')),
                ('investee_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='investee_companies.investeecompany')),
                ('share_capital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='investee_companies.sharecapital')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
