# Generated by Django 5.2.4 on 2025-12-24 16:39

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0001_initial'),
        ('investors', '0001_initial'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='redemptiontransaction',
            name='cost_basis',
        ),
        migrations.AddField(
            model_name='capitalcall',
            name='amount_called_fund_ccy',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=18),
        ),
        migrations.AddField(
            model_name='capitalcall',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=10, default=Decimal('1.0000000000'), help_text="Exchange rate to convert to Fund's functional currency", max_digits=20),
        ),
        migrations.AddField(
            model_name='capitalcall',
            name='transaction_currency',
            field=models.ForeignKey(blank=True, help_text='Currency of the actual cash flow/trade', null=True, on_delete=django.db.models.deletion.PROTECT, to='currencies.currency'),
        ),
        migrations.AddField(
            model_name='distribution',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=10, default=Decimal('1.0000000000'), help_text="Exchange rate to convert to Fund's functional currency", max_digits=20),
        ),
        migrations.AddField(
            model_name='distribution',
            name='gross_amount_fund_ccy',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=18),
        ),
        migrations.AddField(
            model_name='distribution',
            name='transaction_currency',
            field=models.ForeignKey(blank=True, help_text='Currency of the actual cash flow/trade', null=True, on_delete=django.db.models.deletion.PROTECT, to='currencies.currency'),
        ),
        migrations.AddField(
            model_name='drawdownreceipt',
            name='amount_received_fund_ccy',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=18),
        ),
        migrations.AddField(
            model_name='drawdownreceipt',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=10, default=Decimal('1.0000000000'), help_text="Exchange rate to convert to Fund's functional currency", max_digits=20),
        ),
        migrations.AddField(
            model_name='drawdownreceipt',
            name='transaction_currency',
            field=models.ForeignKey(blank=True, help_text='Currency of the actual cash flow/trade', null=True, on_delete=django.db.models.deletion.PROTECT, to='currencies.currency'),
        ),
        migrations.AddField(
            model_name='investorcommitment',
            name='amount_committed_fund_ccy',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=18),
        ),
        migrations.AddField(
            model_name='investorcommitment',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=10, default=Decimal('1.0000000000'), help_text="Exchange rate to convert to Fund's functional currency", max_digits=20),
        ),
        migrations.AddField(
            model_name='investorcommitment',
            name='transaction_currency',
            field=models.ForeignKey(blank=True, help_text='Currency of the actual cash flow/trade', null=True, on_delete=django.db.models.deletion.PROTECT, to='currencies.currency'),
        ),
        migrations.AddField(
            model_name='investorunitissue',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=10, default=Decimal('1.0000000000'), help_text="Exchange rate to convert to Fund's functional currency", max_digits=20),
        ),
        migrations.AddField(
            model_name='investorunitissue',
            name='is_demat',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='investorunitissue',
            name='transaction_currency',
            field=models.ForeignKey(blank=True, help_text='Currency of the actual cash flow/trade', null=True, on_delete=django.db.models.deletion.PROTECT, to='currencies.currency'),
        ),
        migrations.AddField(
            model_name='purchasetransaction',
            name='amount_fund_currency',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=18),
        ),
        migrations.AddField(
            model_name='purchasetransaction',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=10, default=Decimal('1.0000000000'), help_text="Exchange rate to convert to Fund's functional currency", max_digits=20),
        ),
        migrations.AddField(
            model_name='purchasetransaction',
            name='transaction_currency',
            field=models.ForeignKey(blank=True, help_text='Currency of the actual cash flow/trade', null=True, on_delete=django.db.models.deletion.PROTECT, to='currencies.currency'),
        ),
        migrations.AddField(
            model_name='redemptiontransaction',
            name='amount_fund_currency',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=18),
        ),
        migrations.AddField(
            model_name='redemptiontransaction',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=10, default=Decimal('1.0000000000'), help_text="Exchange rate to convert to Fund's functional currency", max_digits=20),
        ),
        migrations.AddField(
            model_name='redemptiontransaction',
            name='settle_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='redemptiontransaction',
            name='transaction_currency',
            field=models.ForeignKey(blank=True, help_text='Currency of the actual cash flow/trade', null=True, on_delete=django.db.models.deletion.PROTECT, to='currencies.currency'),
        ),
        migrations.AlterField(
            model_name='investorunitissue',
            name='investor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_issuances', to='investors.investor'),
        ),
        migrations.AlterField(
            model_name='purchasetransaction',
            name='price',
            field=models.DecimalField(decimal_places=4, help_text='Price in Transaction Currency', max_digits=18),
        ),
        migrations.AlterField(
            model_name='redemptiontransaction',
            name='price',
            field=models.DecimalField(decimal_places=4, help_text='Exit price in Transaction Currency', max_digits=18),
        ),
        migrations.AlterField(
            model_name='redemptiontransaction',
            name='realized_gain',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=18),
        ),
    ]
