# Generated by Django 5.2.4 on 2025-08-29 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investee_companies', '0003_remove_sharecapital_investee_company_and_more'),
        ('transactions', '0002_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasetransaction',
            name='share_capital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='investee_companies.shareholding'),
        ),
        migrations.AlterField(
            model_name='redemptiontransaction',
            name='share_capital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='investee_companies.shareholding'),
        ),
    ]
