# Generated by Django 5.2.4 on 2025-12-24 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0001_initial'),
        ('transactions', '0002_remove_redemptiontransaction_cost_basis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investorunitissue',
            name='reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='purchasetransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=18),
        ),
        migrations.AddField(
            model_name='redemptiontransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=18),
        ),
        migrations.AddField(
            model_name='redemptiontransaction',
            name='cost_basis',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='capitalcall',
            name='amount_called_fund_ccy',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='gross_amount_fund_ccy',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='drawdownreceipt',
            name='amount_received_fund_ccy',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='drawdownreceipt',
            name='capital_call',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='transactions.capitalcall'),
        ),
        migrations.AlterField(
            model_name='investorcommitment',
            name='amount_committed_fund_ccy',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='investorunitissue',
            name='investor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='investors.investor'),
        ),
        migrations.AlterField(
            model_name='investorunitissue',
            name='is_demat',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='purchasetransaction',
            name='price',
            field=models.DecimalField(decimal_places=4, help_text='Price per share (in Txn Currency)', max_digits=18),
        ),
        migrations.AlterField(
            model_name='redemptiontransaction',
            name='price',
            field=models.DecimalField(decimal_places=4, help_text='Selling price per share', max_digits=18),
        ),
        migrations.AlterField(
            model_name='redemptiontransaction',
            name='realized_gain',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
    ]
