# Generated by Django 5.2.4 on 2025-08-30 16:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0002_initial'),
        ('investors', '0002_investordocument_delete_document'),
        ('transactions', '0003_alter_purchasetransaction_share_capital_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cashflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('transaction_type', models.CharField(choices=[('CALL', 'Capital Call (Drawdown)'), ('DISTRIBUTION', 'Distribution / Redemption'), ('EXPENSE', 'Expense'), ('OTHER', 'Other')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('description', models.TextField(blank=True, null=True)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashflows', to='funds.fund')),
                ('investor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cashflows', to='investors.investor')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
