# Generated by Django 5.2.4 on 2025-08-30 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_cashflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='redemptiontransaction',
            name='currency',
            field=models.CharField(default='INR', max_length=3),
        ),
        migrations.AddField(
            model_name='redemptiontransaction',
            name='fees',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='redemptiontransaction',
            name='fx_rate',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=18),
        ),
        migrations.AddField(
            model_name='redemptiontransaction',
            name='taxes',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
    ]
