# Generated by Django 5.2.4 on 2025-08-28 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('sebi_manager_registration_no', models.CharField(blank=True, max_length=64, null=True)),
                ('cin', models.CharField(blank=True, max_length=21, null=True)),
                ('pan', models.CharField(blank=True, max_length=10, null=True)),
                ('gstin', models.CharField(blank=True, max_length=15, null=True)),
                ('registered_address', models.TextField(blank=True, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Manager Entity',
                'verbose_name_plural': 'Manager Entities',
                'ordering': ['name'],
            },
        ),
    ]
