# Generated by Django 5.2.4 on 2025-08-28 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('docgen', '0002_initial'),
        ('investee_companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generateddocument',
            name='investee_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_documents', to='investee_companies.investeecompany'),
        ),
    ]
