# Generated by Django 5.2.4 on 2025-08-28 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('docgen', '0003_initial'),
        ('investors', '0001_initial'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generateddocument',
            name='investor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_documents', to='investors.investor'),
        ),
        migrations.AddField(
            model_name='generateddocument',
            name='purchase_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_documents', to='transactions.purchasetransaction'),
        ),
        migrations.AddField(
            model_name='generateddocument',
            name='redemption_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_documents', to='transactions.redemptiontransaction'),
        ),
        migrations.AddField(
            model_name='generateddocument',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generated_docs', to='docgen.documenttemplate'),
        ),
    ]
