# Generated by Django 5.2.4 on 2025-12-28 19:06

import compliances.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('scope', models.CharField(choices=[('FUND', 'Fund Level (Specific Scheme)'), ('MANAGER', 'Manager Level (Entity Wide)')], default='FUND', max_length=20)),
                ('jurisdiction', models.CharField(choices=[('DOMESTIC', 'SEBI'), ('IFSC', 'IFSCA')], max_length=10)),
                ('applicable_categories', models.CharField(blank=True, help_text="Comma-separated list of categories (e.g., 'CAT_I,CAT_II'). Leave blank if applying to all.", max_length=255)),
                ('frequency', models.CharField(choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('HALF_YEARLY', 'Half Yearly'), ('ANNUALLY', 'Annually'), ('EVENT_BASED', 'Event Based')], default='ANNUALLY', max_length=20)),
                ('first_due_date', models.DateField(blank=True, help_text='Override: If set, the recurring chain starts from this date. If blank, it uses Fund Incorporation Date.', null=True)),
                ('days_after_period', models.IntegerField(default=7, help_text='Days after month/quarter end to set deadline')),
            ],
        ),
        migrations.CreateModel(
            name='ComplianceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=compliances.models.compliance_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ComplianceTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('topic', models.CharField(choices=[('REPORTING', 'Regulatory Reporting'), ('STEWARDSHIP', 'Stewardship & Voting'), ('TAX', 'Tax & Audit'), ('DOCUMENT', 'Transactional/KYC')], default='REPORTING', max_length=20)),
                ('jurisdiction', models.CharField(choices=[('DOMESTIC', 'SEBI (Domestic)'), ('IFSC', 'IFSCA (GIFT City)'), ('TAX', 'Income Tax / TDS')], default='DOMESTIC', max_length=10)),
                ('due_date', models.DateField()),
                ('priority', models.CharField(choices=[('HIGH', 'Critical / High'), ('MEDIUM', 'Medium'), ('LOW', 'Low / Routine')], default='MEDIUM', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('OVERDUE', 'Overdue')], default='PENDING', max_length=20)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('compliance_master', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='compliances.compliancemaster')),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
    ]
