# Generated by Django 5.2.4 on 2025-12-26 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compliances', '0001_initial'),
        ('funds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliancetask',
            name='fund',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compliance_tasks', to='funds.fund'),
        ),
        migrations.AddField(
            model_name='compliancedocument',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='compliances.compliancetask'),
        ),
    ]
