# Generated by Django 5.2.4 on 2025-12-28 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compliances', '0001_initial'),
        ('funds', '0001_initial'),
        ('manager_entities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliancetask',
            name='fund',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fund_compliance_tasks', to='funds.fund'),
        ),
        migrations.AddField(
            model_name='compliancetask',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager_compliance_tasks', to='manager_entities.managerentity'),
        ),
        migrations.AddField(
            model_name='compliancedocument',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='compliances.compliancetask'),
        ),
    ]
