# Generated by Django 5.2.4 on 2025-08-28 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compliances', '0001_initial'),
        ('funds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliancetask',
            name='fund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_tasks', to='funds.fund'),
        ),
    ]
