# Generated by Django 5.2.4 on 2025-08-28 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compliances', '0002_initial'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliancetask',
            name='purchase_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_tasks', to='transactions.purchasetransaction'),
        ),
        migrations.AddField(
            model_name='compliancetask',
            name='redemption_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_tasks', to='transactions.redemptiontransaction'),
        ),
        migrations.AddField(
            model_name='compliancedocument',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='compliances.compliancetask'),
        ),
        migrations.AddIndex(
            model_name='compliancetask',
            index=models.Index(fields=['fund', 'status', 'due_date'], name='compliances_fund_id_c39bf3_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancetask',
            index=models.Index(fields=['topic', 'due_date'], name='compliances_topic_2851ff_idx'),
        ),
    ]
